name: "Batmon DEV"
description: "Monitor various BMS over bluetooth"
url: https://github.com/bezstpav/batmon-ha
version: "1.81-1"
slug: "batmon-dev"
init: false
host_dbus: true
apparmor: true

homeassistant_api: true # http://supervisor/core/api
hassio_api: true        # http://supervisor

# watchdog: true # todo  https://developers.home-assistant.io/docs/add-ons/configuration/

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

services:
  - mqtt:need

discovery:
  - mqtt


options:
  devices:
    - address: 02:00:07:F9:EA:9A
      type: supervolt
      debug: true
    - address: 02:00:07:5F:6E:F9
      type: supervolt
      debug: true
  concurrent_sampling: false
  keep_alive: true
  verbose_log: false
  sample_period: 30
  publish_period: 100
  invert_current: true
  watchdog: true
  expire_values_after: 300
  install_newer_bleak: true
  bt_power_cycle: true
  mqtt_port: 1883
  mqtt_broker: core-mosquitto
  mqtt_user: bms
  mqtt_password: bms

schema:
  devices:
    - address: str
      type: str
      alias: "str?"
      debug: "bool?"
      pin: "str?"
      algorithm: "str?"
      current_calibration: "float?"

  mqtt_user: "str?"
  mqtt_password: "str?"
  mqtt_broker: "str?"
  mqtt_port: "int(1,65535)?"

  concurrent_sampling: "bool"
  invert_current: "bool"
  keep_alive: "bool"
  watchdog: "bool"

  sample_period: "float"
  publish_period: "float?"
  expire_values_after: "float"

  verbose_log: "bool"

  bt_power_cycle: "bool?"
  install_newer_bleak: "bool?"

  influxdb_host: "str?"
  influxdb_username: "str?"
  influxdb_password: "str?"
  influxdb_ssl: "bool?"
  influxdb_verify_ssl: "bool?"
  influxdb_database: "str?"

#  telemetry: "bool?"